name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CFLAGS_BASE: "-Wall -Wextra -std=c99"

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libraylib-dev \
          clang-format \
          clang-tidy \
          clang
    
    - name: Check code formatting
      run: |
        echo "Checking code formatting..."
        if ! clang-format --dry-run --Werror src/*.c src/*.h; then
          echo "❌ Code formatting check failed"
          echo "Run 'make format' to fix formatting issues"
          exit 1
        fi
        echo "✅ Code formatting check passed"
    
    - name: Build project
      run: |
        echo "Building project..."
        make clean
        if ! make; then
          echo "❌ Build failed"
          exit 1
        fi
        echo "✅ Build successful"
    
    - name: Run static analysis
      run: |
        echo "Running static analysis..."
        if ! clang --analyze $CFLAGS_BASE -O2 src/*.c; then
          echo "⚠️ Static analysis found issues"
        else
          echo "✅ Static analysis passed"
        fi
    
    - name: Run linter
      run: |
        echo "Running linter..."
        if ! clang-tidy src/*.c -- $CFLAGS_BASE; then
          echo "⚠️ Linter found issues (non-blocking)"
        else
          echo "✅ Linting passed"
        fi
      continue-on-error: true
    
    - name: Test build configurations
      run: |
        echo "Testing debug build..."
        make clean
        make debug
        echo "✅ Debug build successful"
        
        echo "Testing release build..."
        make clean  
        make release
        echo "✅ Release build successful"
    
    - name: Verify CI script works
      run: |
        chmod +x scripts/ci-check.sh
        echo "Running local CI script for comparison..."
        ./scripts/ci-check.sh || echo "⚠️ Local CI script has different behavior"